### ISSUE TITLE
Remove Jupyter notebook

### ISSUE THREAD

**Issue by artfisica** [atlas-outreach-data-tools/atlas-outreach-Python-uproot-framework-13tev#2]
Hi @meevans1,

I suggest removing the file called "HZZ.ipynb"
* https://github.com/atlas-outreach-data-tools/atlas-outreach-Python-uproot-framework-13tev/blob/master/HZZ.ipynb

Of course, I don't know if this notebook is relevant in the framework.
But maybe you can add it to the notebooks repo (in case it is different from the two that are already there)
 
Cheers,
Arturo

**Comment by meevans1** [comment]
Hi @artfisica 

Thanks for spotting this.
I've removed the .ipynb files from this repo.
They're the same as those in the notebooks repo.

Cheers
Meirin
